//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PoslovnaLogika.WSKadrovskiPodaci {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OgranicenjaZaposljavanjaSoap", Namespace="http://tempuri.org/")]
    public partial class OgranicenjaZaposljavanja : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DajSvaOgranicenjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DajMaxBrojNastavnikaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OgranicenjaZaposljavanja() {
            this.Url = global::PoslovnaLogika.Properties.Settings.Default.PoslovnaLogika_WSKadrovskiPodaci_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DajSvaOgranicenjaCompletedEventHandler DajSvaOgranicenjaCompleted;
        
        /// <remarks/>
        public event DajMaxBrojNastavnikaCompletedEventHandler DajMaxBrojNastavnikaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DajSvaOgranicenja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DajSvaOgranicenja() {
            object[] results = this.Invoke("DajSvaOgranicenja", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DajSvaOgranicenjaAsync() {
            this.DajSvaOgranicenjaAsync(null);
        }
        
        /// <remarks/>
        public void DajSvaOgranicenjaAsync(object userState) {
            if ((this.DajSvaOgranicenjaOperationCompleted == null)) {
                this.DajSvaOgranicenjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDajSvaOgranicenjaOperationCompleted);
            }
            this.InvokeAsync("DajSvaOgranicenja", new object[0], this.DajSvaOgranicenjaOperationCompleted, userState);
        }
        
        private void OnDajSvaOgranicenjaOperationCompleted(object arg) {
            if ((this.DajSvaOgranicenjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DajSvaOgranicenjaCompleted(this, new DajSvaOgranicenjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DajMaxBrojNastavnika", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DajMaxBrojNastavnika(string pomSifraZvanja) {
            object[] results = this.Invoke("DajMaxBrojNastavnika", new object[] {
                        pomSifraZvanja});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DajMaxBrojNastavnikaAsync(string pomSifraZvanja) {
            this.DajMaxBrojNastavnikaAsync(pomSifraZvanja, null);
        }
        
        /// <remarks/>
        public void DajMaxBrojNastavnikaAsync(string pomSifraZvanja, object userState) {
            if ((this.DajMaxBrojNastavnikaOperationCompleted == null)) {
                this.DajMaxBrojNastavnikaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDajMaxBrojNastavnikaOperationCompleted);
            }
            this.InvokeAsync("DajMaxBrojNastavnika", new object[] {
                        pomSifraZvanja}, this.DajMaxBrojNastavnikaOperationCompleted, userState);
        }
        
        private void OnDajMaxBrojNastavnikaOperationCompleted(object arg) {
            if ((this.DajMaxBrojNastavnikaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DajMaxBrojNastavnikaCompleted(this, new DajMaxBrojNastavnikaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DajSvaOgranicenjaCompletedEventHandler(object sender, DajSvaOgranicenjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DajSvaOgranicenjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DajSvaOgranicenjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DajMaxBrojNastavnikaCompletedEventHandler(object sender, DajMaxBrojNastavnikaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DajMaxBrojNastavnikaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DajMaxBrojNastavnikaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591