//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace KorisnickiInterfejs
{


     public partial class Login1
     {

          /// <summary>
          /// KorisnickoImeTextBox control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox KorisnickoImeTextBox;

          /// <summary>
          /// SifraTextBox control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox SifraTextBox;

          /// <summary>
          /// lblStatus control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblStatus;

          /// <summary>
          /// PrijavaButton control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Button PrijavaButton;

          /// <summary>
          /// OdustaniButton control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Button OdustaniButton;
     }
}
